# Generated by Django 4.2.30 on 2026-06-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_auto_20230710_1506"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="mpesa_payout_number",
            field=models.CharField(
                blank=True,
                help_text="Kenyan M-Pesa number for owner payouts (e.g. 2547XXXXXXXX)",
                max_length=20,
                verbose_name="M-Pesa payout number",
            ),
        ),
    ]
