#!/bin/bash

##this script purpose ensures that we get connected on the database service before we spin any other service in container

##if any command on code fails for any reason, then the entire shell script fails
set -o errexit

##fail exit if one of pipe commands fails
set -o pipefail

##this exits if any of variables is not set
set -o nounset

# For SQLite development, we don't need to wait for PostgreSQL
echo "Using SQLite database for development"

exec "$@"