# Generated by Django 3.2.7 on 2023-08-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='geom',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='car',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='car',
            name='lon',
        ),
    ]
