# Generated by Django 3.2.7 on 2025-08-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='location',
        ),
        migrations.AddField(
            model_name='car',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Full Address'),
        ),
        migrations.AddField(
            model_name='car',
            name='current_location',
            field=models.CharField(blank=True, help_text="Current location description (e.g., 'Nairobi CBD, Kenya')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether the car is currently available for booking', verbose_name='Available for Rent'),
        ),
        migrations.AddField(
            model_name='car',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Car's latitude coordinate", max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='car',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Car's longitude coordinate", max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='car',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['latitude', 'longitude'], name='cars_car_latitud_a8381c_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['city', 'state'], name='cars_car_city_526cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_available', 'published_status'], name='cars_car_is_avai_8b7f32_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price', 'is_available'], name='cars_car_price_640c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['car_type', 'is_available'], name='cars_car_car_typ_22c508_idx'),
        ),
    ]
