# Generated by Django 3.2.7 on 2025-09-07 13:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20250819_1209'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='car',
            name='cars_car_latitud_a8381c_idx',
        ),
        migrations.RemoveField(
            model_name='car',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='car',
            name='longitude',
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text="Car's geographical location (latitude, longitude)", null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['location'], name='cars_car_locatio_517a6c_idx'),
        ),
    ]
