# Generated by Django 3.2.7 on 2023-08-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='total_seats',
            field=models.IntegerField(default=0, verbose_name='Number of Seats'),
        ),
    ]
