# Generated by Django 4.2.30 on 2026-06-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_auto_20250907_1621"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="currency",
            field=models.CharField(
                default="KES", max_length=3, verbose_name="Currency"
            ),
        ),
    ]
