# Generated by Django 4.2.30 on 2026-06-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="owner_payout_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="owner_payout_mpesa_receipt",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="owner_payout_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
