# Generated by Django 3.2.7 on 2025-08-19 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, help_text="User's current latitude coordinate", max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, help_text="User's current longitude coordinate", max_digits=9, verbose_name='Longitude')),
                ('address', models.CharField(blank=True, help_text="User's current address", max_length=500, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, help_text="User's current city", max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, help_text="User's current state or province", max_length=100, null=True, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, help_text="User's current country", max_length=100, null=True, verbose_name='Country')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When the location was last updated', verbose_name='Last Updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this location is currently active', verbose_name='Location Active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Location',
                'verbose_name_plural': 'User Locations',
            },
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['latitude', 'longitude'], name='users_userl_latitud_7a18c4_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['city', 'state'], name='users_userl_city_6e39bc_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['is_active'], name='users_userl_is_acti_67883e_idx'),
        ),
    ]
