# Generated by Django 3.2.7 on 2025-09-07 13:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250819_1209'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userlocation',
            name='users_userl_latitud_7a18c4_idx',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='userlocation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text="User's current geographical location (latitude, longitude)", null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['location'], name='users_userl_locatio_a6f4e5_idx'),
        ),
    ]
