# Generated by Django 4.2.30 on 2026-06-22 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20250907_1621"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("otp_code", models.CharField(max_length=8)),
                (
                    "otp_type",
                    models.CharField(
                        choices=[
                            ("login", "Login Verification"),
                            ("registration", "Registration Verification"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_otps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTPAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provided_code", models.CharField(max_length=8)),
                ("is_successful", models.BooleanField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "otp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_attempts",
                        to="users.otp",
                    ),
                ),
            ],
            options={
                "db_table": "otp_attempts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["phone_number", "otp_type", "is_used"],
                name="user_otps_phone_n_d625a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["expires_at"], name="user_otps_expires_5a164f_idx"
            ),
        ),
    ]
