# Generated by Django 4.2.30 on 2026-06-24 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_pickup_mileage_booking_pickup_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="rating",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="renter_review",
                to="bookings.booking",
                verbose_name="Booking",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rater",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews_given",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User providing the rating",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "Poor"),
                    (2, "Fair"),
                    (3, "Good"),
                    (4, "Very Good"),
                    (5, "Excellent"),
                ],
                help_text="1=Poor, 2=Fair, 3=Good, 4=Very Good, 5=Excellent",
                verbose_name="Rating",
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                condition=models.Q(("booking__isnull", False)),
                fields=("booking",),
                name="unique_review_per_booking",
            ),
        ),
    ]
