# Generated by Django 4.2.30 on 2026-06-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_activated_at_booking_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="pickup_mileage",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="handover/pickup/"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="return_mileage",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="return_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="return_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="handover/return/"
            ),
        ),
    ]
