# Generated by Django 4.2.30 on 2026-06-24 11:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_pickup_mileage_booking_pickup_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="location_sharing_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Renter opted in to share GPS during this active rental",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="location_sharing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BookingLocationPing",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("accuracy_m", models.FloatField(blank=True, null=True)),
                ("speed_kmh", models.FloatField(blank=True, null=True)),
                ("heading", models.FloatField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField()),
                (
                    "source",
                    models.CharField(
                        choices=[("renter_phone", "Renter phone")],
                        default="renter_phone",
                        max_length=20,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_pings",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["booking", "-recorded_at"],
                        name="bookings_bo_booking_8a7da5_idx",
                    )
                ],
            },
        ),
    ]
